//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PyramidTimesWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminEvent
    {
        public int Id { get; set; }
        public string EventName { get; set; }
        public string PromoVideo { get; set; }
        public string CauroselPicture { get; set; }
        public string Descrption { get; set; }
        public Nullable<System.DateTime> EventTime { get; set; }
        public string PromoPicture { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> SpeakerId { get; set; }
    }
}
